### ISSUE TITLE
Potential inspiration

### ISSUE THREAD

**Issue by dumblob** [Hejsil/ston#1]
Hi, I've just seen new activity in my feed and thought you might be interested in one of my older crazy write-ups - https://github.com/dumblob/uSX .

Feel free to close this issue as you see fit and good luck with *ston* :wink:

**Comment by Hejsil** [comment]
Cool stuff! Seems to be some overlap, but `uSX` as an idea seems more complicated than what I need from `ston`. Thanks for sending this my way, though. It's cool to get a different perspective on a similar idea :)
